---
output:
  html_document: default
  
---
```{r instructions, include=FALSE}
#Instructions:

# This file will read in your clean validation dataset, created after
# running "Step1.DataCleaning.R"
# 2 datasets will be created which will be used for calibration:
# 1) valdata : This captures cases in years 1-5 from baseline.
# 2) valdata2: This captures cases in years 2-6 from baseline. 

# After specifying the date and filepaths, (ctrl+f: "filepath" for where to insert), you can simply:
# hit "Knit -> Knit to Word" and this will run the full document and produce output.

# Please send the finalized document to kristen_brantley@dfci.harvard.edu
# If any issues arise when trying to run this document, please reach out to Kristen Brantley.

# Below, PLEASE INSERT COHORT ACRONYM IN [] BELOW 
# AND INSERT RUN DATE
```

---
title: "Create 2 datasets [CTS]"
output: html_document
date: "MM-DD-YYYY"
---

```{r setup, include=FALSE}
options(knitr.duplicate.label="allow")
```

```{r load, include=FALSE, echo=FALSE}
if(!require(tidyverse)){
  install.packages("tidyverse")
  suppress.warnings(library("dplyr"))
}
if(!require(lubridate)){
  install.packages("lubridate")
  suppress.warnings(library("lubridate"))
}
```

```{r data, include=FALSE}
#Please read in your CLEAN file below where bcrpp_valdata.csv is specified.
valdata<-read.csv("FILEPATH/bcrpp_valdata.csv")

```

## Case numbers and prevalent cases in original dataset, overall and by race

```{r describe}
#Describe case #s
table(valdata$case, useNA="always")
table(valdata$case_invasive, useNA="always")
table(valdata$prevalent_case_primary1, useNA="always")
table(valdata[which (valdata$prevalent_case_primary1==1),]$case_invasive , useNA="always")

table(valdata$race, valdata$case)
table(valdata[which (valdata$race==2),]$case, useNA="always")
table(valdata[which (valdata$race==2),]$case_invasive, useNA="always")
table(valdata[which (valdata$race==2),]$prevalent_case_primary1, useNA="always")
table(valdata[which (valdata$race==2 & valdata$case_invasive==1),]$prevalent_case_primary1, useNA="always")
```

```{r new, include=FALSE}
#Delete prevalent cases or cases missing time to dx
valdata<-valdata[which (valdata$prevalent_case_primary1==0),]
#only an issue here if time is missing and case_invasive b/c we are testing invasive model
notime<-valdata[which (valdata$case_invasive==1 & is.na(valdata$time_bltodx1)),]
valdata<-valdata[which (!valdata$id %in% notime$id),]
```


## Final valdata: Cases in 5y and invasive cases in 5y
```{r finalnums}
table(valdata$case_5y, useNA="always")
table(valdata$case_5yinv, useNA="always")
```

```{r new2, include=FALSE}
#Create dataset that starts at year 2
drops1<-valdata[which (!is.na(valdata$timediff_case) & valdata$timediff_case<2),]
table(drops1$timediff_case, drops1$case)
drops2<-valdata[which (!is.na(valdata$timediff_control) & (valdata$case==0) & valdata$timediff_control<2),]
drops<-c(drops1$id, drops2$id)

valdata2<-valdata[which (!valdata$id %in% drops),]
```

```{r chunk, include=FALSE}
#Age to age+1 as starting age
#Meno status changed if changed within 1 y of record

valdata2<-valdata2 %>%
  mutate(age=age+1,
         meno_status2=ifelse(meno_age<=age & !is.na(meno_age), 2, 
                             ifelse(meno_age>=age & !is.na(meno_age), meno_status2, meno_status2)))
```

## Final case numbers for valdata2, overall and invasive

```{r final nums2}
#final valdata2, cases in years 2-6, invasive cases in years 2-6
table(valdata2$case_6y, useNA="always")
table(valdata2$case_6yinv, useNA="always")
```

## Overall numbers for datasets

```{r dim}
#size of datasets: valdata
dim(valdata)
#size of datasets: valdata2
dim(valdata2)

```
```{r}
#Please insert filepath herewhere your .Rmd document is saved
rmarkdown::render("C:/Users/krist/Dropbox/BCRPProject/Code/Model Calibration/External Code/Step2.Create2datasets.Rmd")
```