---
title: "Step2.Create2datasets_BWHS"
output: html_document
date: "2025-04-16"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(knitr.duplicate.label="allow")
```

```{r setup, include=FALSE}
if(!require(tidyverse)){
  install.packages("tidyverse")
  library("dplyr")
}
if(!require(lubridate)){
  install.packages("lubridate")
  library("lubridate")
}
```

##Case numbers and prevalent cases for dataset black women only

```{r chunk1}

#Please read in your CLEAN file if you have not just run the file. You can also source Step1_Clean_CTS.R
valdata<-read.csv("FILEPATH/bcrpp_valdata.csv")

#Drop if age is <30 or age is >70 or if not black

drops<-c("V1")
valdata<-valdata[,!(names(valdata) %in% drops),]
valdata<-valdata[which (valdata$race==2),]
valdata<-valdata[which (valdata$age>=30 & valdata$age<=70),]

table(valdata$case, useNA="always")
table(valdata$case_invasive, useNA="always")
table(valdata$prevalent_case_primary1, useNA="always")
table(valdata[which (valdata$prevalent_case_primary1==1),]$case_invasive , useNA="always")

```

```{r include=FALSE}
#Delete prevalent cases 
valdata<-valdata[which (valdata$prevalent_case_primary1==0),]

#Delete cases missing time to dx because timing is needed.
#only an issue here if time is missing and case_invasive b/c we are testing invasive model
notime<-valdata[which (valdata$case_invasive==1 & is.na(valdata$time_bltodx1)),]
valdata<-valdata[which (!valdata$id %in% notime$id),]

#If non-invasive case is missing time diff it will be an issue, so need to correct - make assumption it is across interval
valdata$timediff<-ifelse(is.na(valdata$timediff),10, valdata$timediff )
```

## Case numbers and prevalent cases in 1-5y followup dataset

```{r}
#valdata is the dataset for 0-5 y, excludes prevalent cases.
table(valdata$case_5y)
table(valdata$case_5yinv)
```

```{r chunk2, echo=FALSE}
######################################
#Create dataset that starts at year 2
######################################

#drop cases before year 2
drops1<-valdata[which (!is.na(valdata$timediff_case) & valdata$timediff_case<2),]
#table(drops1$timediff_case, drops1$case)

#drop controls that exit before year 2
drops2<-valdata[which (!is.na(valdata$timediff_control) & (valdata$case==0) & valdata$timediff_control<2),]

drops<-c(drops1$id, drops2$id)
#table(valdata$case, valdata$timediff_control)

valdata2<-valdata[which (!valdata$id %in% drops),]

#Age to age+1 as starting age
#Meno status changed if changed within 1 y of record

valdata2<-valdata2 %>%
  mutate(age=age+1,
         meno_status2=ifelse(meno_age<=age & !is.na(meno_age), 2, 
                             ifelse(meno_age>=age & !is.na(meno_age), meno_status2, meno_status2)))

```


## Case numbers and prevalent cases in 2-6y followup dataset

```{r}
#valdata2 is the dataset for cases 2-6y. 
table(valdata2$case_6y)
table(valdata2$case_6yinv)
```

```{r instructions, include=FALSE}
#You will now need to run rmarkdown::render in your R Console. This cannot be included in the .Rmd file directly, or it will iteratively run.
#Please enter this code into the console:
#     rmarkdown::render("FILEPATH/Step2.Create2datasets_BWHS.Rmd")
#The resulting .html file will be called Ext_Model_Calibration_Gail as well, and will be found in the same file path as that of your .Rmd file.
```